### PR TITLE
Use vscode upcoming multiline messages

### PR DESCRIPTION
**Pull request by doudou**
Built on top of #5.

This should be left here until the relevant changes in VSCode are itself merged.

Depends on:
- [x] https://github.com/Microsoft/vscode/pull/39935
- [x] https://github.com/Microsoft/vscode/pull/39936

### CODE REVIEW

**Comment by g-arjones** [comment]
Multiline problem matchers made it into vscode 1.21. I have rebased this and set problematic files' path as being relative. Although, it seems that it only works when the package is built for the first time.. Could you check that?

**Comment by doudou** [comment]
Well ... making paths relative should either not work or be brittle with autoproj, since the autoproj cwd can virtually be anything (and is definitely not guaranteed to be the packages' path :()

We could try the solution suggested here: https://cmake.org/pipermail/cmake/2014-March/057164.html

**Comment by doudou** [comment]
Note that I don't understand how this would even work with "pure cmake" when using separate build dirs. AFAIK, one has to run within the cmake build dir, so the relative path would not resolve properly either.

**Comment by doudou** [comment]
For what it's worth, I might start working on attaching whole backtraces to problems in VSCode. It bites me at every turn, whatever the language. C++ template instanciation right now is basically impossible to go through in the problem view.

**Comment by doudou** [comment]
For reference, the problem matchers for C++ inclusion and template instanciation error traces: https://github.com/rock-core/vscode-rock/pull/52

**Comment by g-arjones** [comment]
> and is definitely not guaranteed to be the packages' path

Good point. In this case I would remove the "field" property from the pattern (or leave at as relative and just accept to have it working only "sometimes" rather than "never").

> C++ template instanciation

Those are a major pain.

Could you get the multiline matchers to work consistently? In my tests I only got it to work once per package (which is pretty weird)

**Comment by doudou** [comment]
> Could you get the multiline matchers to work consistently? In my tests I only got it to work once per package (which is pretty weird)

I haven't re-tried, I really need to focus on the project stuff right now (from which a bunch of syskit and roby bugs get triggered and fixed as you have seen)

**Comment by g-arjones** [comment]
No problem..

**Comment by doudou** [comment]
Same here ... I close this, we'll reopen when someone starts working on it again.

**Comment by g-arjones** [comment]
I will do it...

**Comment by g-arjones** [comment]
There was a bug in a regex. Fixed and seems to work now..

Making the file location relative should work in most cases, AFAICT. Autoproj's cwd is not relevant, cmake always output file locations relative to the CMAKE_BINARY_DIR and vscode expands them to `${workspaceFolder}`, regardless of the cwd in both cases. Problem is, for the workspace folder to be correct, the task provider must set the task's scope to folder path (using the new constructor).

Since we are not doing this yet, I am leaving the file location as absolute for now...

**Pull request merged**
