### PR TITLE
Provide launch configuration snippets

### PR DESCRIPTION
**Pull request by g-arjones**
@doudou Could you give this a try when you get the time? Please let me know what you think about it..
 
Open a launch.json and try to add a new entry either by using intellisense or by clicking the "Add Configuration..." blue button

### CODE REVIEW

**Comment by g-arjones** [comment]
I had further plans but I think this is good enough for the 0.1 release. We need to refactor the packages module at some point (I don't think we need all those subclasses anymore).

**Comment by doudou** [comment]
It's broken on orogen config: the `deploy` and `name` field have `Task` inserted in front (`Taskimu_advanced_navigation_anpp::Task`)

Asking for completion with intellisense does not work either (it offers no suggestions) even though the code goes through the snippets. Was it supposed to work ?

**Comment by g-arjones** [comment]
> It's broken on orogen config: the deploy and name field have Task inserted in front (Taskimu_advanced_navigation_anpp::Task)

I will have a look...

> Asking for completion with intellisense does not work either (it offers no suggestions) even though the code goes through the snippets. Was it supposed to work ?

The snippets are for the entire launch entry, not within an specific launch entry, i.e:
```
{
    "version": "0.2.0",
    "configurations": [
         <place the carret here and hit ctrl+space>

         {
             name: "..."
             ...
         }
    ]
}
```

**Comment by g-arjones** [comment]
I think I have fixed the bogus entry issue. Could you please test it again?

**Comment by doudou** [comment]
Yep, works this time.

**Pull request merged**
