### PR TITLE
Autoproj

### PR DESCRIPTION
**Pull request by g-arjones**

### CODE REVIEW

**Comment by g-arjones** [comment]
I had to spend some time learning typescript.. turns out, it is not that bad indeed. I would say that, aside from some refactoring and a few unit tests, the only thing missing for a pre-alpha release are the debug tasks.

**Comment by doudou** [comment]
Cool. :+1:

FYI, I'm in vacation next week, so won't be doing much until after Christmas

**Comment by g-arjones** [comment]
Nice... Going to France? Enjoy the holidays! 👍

**Comment by doudou** [comment]
> Going to France? Enjoy the holidays! :+1:

Thanks. Much better than France, I'm going on a trip in the Amazon.

**Pull request merged**
